name: dhis2_demo_app
description: A DHIS2 demo app for demonstrating how flutter can be used to build DHIS2 mobile apps.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flex_color_scheme: ^6.1.2
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

